# PROJECT_NAME: multiInstanceUserCreation
# CREATED BY: AALEEM SIDDIQUI
# DESCRIPTION: This pipeline converts a normal user to a multi-Instance user as well as adding new Instances to an already multi-Instance user. 
# -------------------------------------

image: busybox:latest

stages:
  - createMultiInstanceUser

# -------------------------------------

variables:
  EXISTING_INSTANCES: 
    value: ""
    description: "List of existing Instance names for the user. Example: instance1,instance2,etc..."
  NEW_INSTANCE: 
    value: ""
    description: "The new Instance name the user will be added to. Example: instance3"
  USER_EMAIL: 
    value: ""
    description: "The e-mail address tied to the user. Example: aaleemsiddiqui@gmail.com"
  GROUP_ASSIGNMENT:
    value: "Administrator"
    description: "The permission level of the user within the new Instance."
    options:
      - "Administrator"
      - "User"
      - "Visitor"
  CLUSTER_NAME:
    value: "cluster1"
    description: "The name of the Cluster."
    options:
      - "cluster1"
      - "cluster2"
      - "cluster3"

# -------------------------------------

createMultiInstanceUser:
  stage: createMultiInstanceUser
  script:
    - /bin/bash createMultiInstanceUser.sh -t $EXISTING_INSTANCES -n $NEW_INSTANCE -e $USER_EMAIL -c $CLUSTER_NAME -g $GROUP_ASSIGNMENT

