# PROJECT_NAME: generateSignupLink
# CREATED BY: AALEEM SIDDIQUI
# DESCRIPTION: Often times the initial welcome e-mail for a user to login to their instance is lost, this pipeline generates that link with a new token. 
# -------------------------------------

image: busybox:latest

stages:
  - generateInvitationLink

# -------------------------------------

variables:
  CLIENT_EMAIL:
    value: ""
    description: "The email address of the client / Instance owner. Example: aaleemsiddiqui@gmail.com"
  INSTANCE_NAME:
    value: ""
    description: "The name of the Instance. Example: Instance1"
  CLUSTER_NAME:
    value: "cluster1"
    description: "The name of the Cluster."
    options:
      - "cluster1"
      - "cluster2"
      - "cluster3"

# -------------------------------------

generateInvitationLink:
  stage: generateInvitationLink
  script:
    - /bin/bash recreate_signup.sh -e $CLIENT_EMAIL -t $INSTANCE_NAME -c $CLUSTER_NAME